Answering my own question since it just caught me out ...
-------------------------------------------------------------------------------

36. My thorn is calling directly a function from another thorn. Both thorns
    are in my ThornList, but on linking I get the error

    Startup.c.o(.text+0x4d): undefined reference to `OtherThornsFunction'

    Make sure that your thorn inherits from the implementation provided by
    the other thorn. If you don't do this, the end link line may not list
    the libraries in the right order for linking.

-------------------------------------------------------------------------------


git-svn-id: https://svn.cactuscode.org/flesh/trunk@2917 17b73243-c579-4c4c-a9d2-2d5706c11dac